export { default as GmailIcon } from "./Gmail";
export { default as InstagramIcon } from "./Instagram";
export { default as NotionIcon } from "./Notion";
export { default as SelectedDislikeIcon } from "./SelectedDislike";
export { default as SelectedLikeIcon } from "./SelectedLike";
export { default as TelegramIcon } from "./Telegram";
export { default as TwitterIcon } from "./Twitter";
export { default as VkIcon } from "./Vk";
export { default as YoutubeIcon } from "./Youtube";
